services:
  app:
    build: 
        context: ../
        dockerfile: ./trading/Dockerfile
    container_name: automatic-trading-container
    env_file:
      - ./.env
    tty: true
    stdin_open: true